### PR TITLE
Fix safari sso

### LINKED ISSUE #1473: SSO from Browser Extension Does not Login Browser Extension
## Describe the Bug

When initiating Enterprise SSO from the browser extension, the user is taken through the web vault's SSO flow (expected), after IdP authentication, the user is redirected back through another round-trip and then logged into the web vault (unexpected); the browser extension remains logged out/unauthenticated (unexpected).

## Steps To Reproduce

1. Open the browser extension, click `Enterprise Single Sign-On` button
2. In the new tab, enter in your organization's identifier and click `Log In`
3. Authenticate with your IdP
4. Note you are back at the prompt for your organization's identifier, should be pre-filled
5. Click `Log In` again
6. Note you are at the web vault's Unlock screen, prompted to enter your master password
7. Enter your master password and click "Unlock"
8. Note you are logged into the web vault only, the browser extension remains logged out

## Expected Result

After successfully authenticating with your IdP, the user should be shown a message to close their browser tab and the browser extension should be logged in, however the user would still have to enter their master password into the browser extension to gain access and enable decryption of their vault data.

## Actual Result

User is only logged into the web vault (after several round trips) and the browser extension remains in a logged out state.

## Screenshots or Videos

Screen Recording - SSO Browser Extension Login

## Environment

- Operating system: All
- Browser: All; testing in Firefox, Chrome, Brave, Safari, and Edge
- Build Version (go to "Settings" → "About" in the app): Browser Ext: 1.47.0, Web: 2.17.0

## Additional Context

This has been reported by several folks over the last week.

see related PRs:
 * https://github.com/bitwarden/browser/pull/1472
 * https://github.com/bitwarden/jslib/pull/210
 * https://github.com/bitwarden/jslib/pull/211
 * https://github.com/bitwarden/web/pull/720

### PR DESCRIPTION
**Pull request by MGibson1**
# Overview

Closes #1473. Safari SSO sign on from browser is still broken. Full SSO process is triggered, but final tab open to the SSO extension component does not work. We need to get Safari responding correctly to messages in all contexts.

# Files Changed

* **safariApp.ts**: webkit message handlers is not available from a tab opened to an extension resource. In this context, we should use safari.extension.dispatchMessage as done elsewhere.
* **content/sso.ts**: Safari app extension does not respond to chrome.runtime. Use dispatchMessage here too.
* **SafariExtensionsViewController.swift**: `createNewTab` messages for extension resources are delivered as path?query URIs only, which Safari does not interpret correctly. Detect these types of paths and navigate to the appropriate resource

### CODE REVIEW

**Review by kspearrin — APPROVED** [review]

**Review by cscharf — CHANGES_REQUESTED** [review]
Please refer to prior discussion on message command + handling in the swift to navigate the pop-up vs. opening another tab.

**Comment by MGibson1** [comment]
Thanks @cscharf for the tip on abandoning tab loading and pushing the sso to the popover, which is even better!

The changes necessary are all in **SafariExtensionsViewController.swift**.

File: src/safari/safari/SafariExtensionViewController.swift [hunk 1]
```diff
@@ -16,27 +16,36 @@ class SafariExtensionViewController: SFSafariExtensionViewController, WKScriptMe
...
-        webView.loadFileURL(url!, allowingReadAccessTo: bundleURL)
+        navigateWebView("app/popup/index.html")
         webView.alphaValue = 0.0
         webView.uiDelegate = self
         view.addSubview(webView)
     }
 
+    func navigateWebView(_ relativeUrl: String){ 
+        let version = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String
+        let bundleUrl = Bundle.main.resourceURL!.absoluteURL
```
Comment (cscharf) [inline src/safari/safari/SafariExtensionViewController.swift:38]: Only hesitation around this is the use of the `!` operator to explicitly cast the `resourceURL` without a `nil` check and/or using safe unwrapping, `if let resourceUrl = Bundle.main.resourceURL {` ... but not sure if that's necessary.

File: src/safari/safari/SafariExtensionViewController.swift [hunk 2]
```diff
@@ -16,27 +16,36 @@ class SafariExtensionViewController: SFSafariExtensionViewController, WKScriptMe
...
+
+        var urlComponents = URLComponents(string: bundleUrl.appendingPathComponent(relativeUrl).absoluteString)
+
+        if (urlComponents?.queryItems?.first(where: { $0.name == "appVersion" })?.value == nil) {
+            urlComponents?.queryItems?.append(URLQueryItem(name: "appVersion", value: version))
+        }
+
+        webView.loadFileURL(urlComponents!.url!, allowingReadAccessTo: bundleUrl)
```
Comment (cscharf) [inline src/safari/safari/SafariExtensionViewController.swift:46]: Same here... `urlComponents` when I tested appears to be `nil` but not sure when it wouldn't be, etc.

image

**Review by cscharf — COMMENTED** [review]
Appears the popup is now opening, which is awesome! However, the extension is still not getting logged in (see other review comments as well on `nil` handling and casting/unwrapping)

image

File: src/safari/safari/SafariExtensionViewController.swift (hunk 1 above)
Comment (MGibson1) [reply src/safari/safari/SafariExtensionViewController.swift:38]: This particular line is a copy from line 25 of original file.

I'm fine dealing with the `nil`, but what do you think the behavior should be if it is? Just return? This is what I'm doing in the latest iteration.

File: src/safari/safari/SafariExtensionViewController.swift (hunk 2 above)
Comment (MGibson1) [reply src/safari/safari/SafariExtensionViewController.swift]: Sorry about this, it's due to my messed up workflow for working in xcode and missed committing the latest changes.

It should be better handled and working now.

File: src/safari/safari/SafariExtensionViewController.swift (hunk 1 above)
Comment (cscharf) [reply src/safari/safari/SafariExtensionViewController.swift:38]: No, should be fine if it was working okay before.

**Review by cscharf — APPROVED** [review]
it WORKS!!!! 😁  🎉
