### PR TITLE
Close 2fa window if redirected from sso login

### LINKED ISSUE #1479: SSO in Browser Extension Leaves multiple tabs open
## Describe the Bug

This is a follow-up issue discovered after resolution of https://github.com/bitwarden/browser/issues/1473.

## Steps To Reproduce

1. Install the latest browser extension on Chrome, v1.47.1
2. Click on Enterprise Sing Sign-On
3. Authenticate in the new tab
4. Finish any 2FA + master password unlock in new tab

## Expected Result

The browser extension itself is navigated to the appropriate screen and the user is prompted to close the 1 tab and open the extension to complete the log in process.

## Actual Result

A 2nd tab is opened which completed the log in process and stays open; but has the same address as the chrome extension itself.

## Screenshots or Videos

This tab is expected to be left open (and is 👍🏻 )
image

This tab is **not** expected to be left open, or to be opened at all (but is 👎🏻 )
image

Here's a video of the behavior:
browser-extension-behavior

## Environment

- Operating system: macOS Catalina
- Browser: Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Build Version 1.47.1

cc: @clayadams5226 , @MGibson1

### PR DESCRIPTION
**Pull request by MGibson1**
# Objective

Closes 2fa window if the window was opened as part of an sso login. Reduces the number of hanging tabs left open from sso flow.

Closes #1479 

# Files Changed

* **main.background.ts**: linter fix, just removed from whitespace.
* **two-factor.component.ts**: subscribe to query parameters and alter onSuccessfulLogin event handler to close the current window.

## Commit messages
This is a workaround until we can get browser extension sso to use the
toolbar popup.

main.background.ts is a linter autofix

### CODE REVIEW

File: src/popup/accounts/two-factor.component.ts [hunk 1]
```diff
@@ -80,6 +81,20 @@ export class TwoFactorComponent extends BaseTwoFactorComponent {
                 this.popupUtilsService.popOut(window);
             }
         }
+
+        const queryParamsSub = this.route.queryParams.subscribe(async (qParams) => {
+            if (qParams.sso != null && qParams.sso === 'true') {
```
Comment (cscharf) [inline src/popup/accounts/two-factor.component.ts:86]: Can't you just test `qParams.sso === 'true'` w/o the `null` check?

File: src/popup/accounts/two-factor.component.ts [hunk 2]
```diff
@@ -80,6 +81,20 @@ export class TwoFactorComponent extends BaseTwoFactorComponent {
...
+                    BrowserApi.reloadOpenWindows();
+                    const thisWindow = window.open('', '_self');
+                    thisWindow.close();
+                    return this.syncService.fullSync(true);
+                }
+                if (queryParamsSub != null) {
+                    queryParamsSub.unsubscribe();
+                }
+            }
+        })
```
Comment (cscharf) [inline src/popup/accounts/two-factor.component.ts:97]: semi-colon, `;`

**Review by cscharf — APPROVED** [review]
