### PR TITLE
Fix totp copy not working in Chrome

### LINKED ISSUE #2053: TOTP not copying after selecting login item.
## Describe the Bug
When using the Bitwarden extension from the Chrome Web Store, the extension does not automatically copy the TOTP after clicking on the appropriate login from the extension.

## Steps To Reproduce
1. Go to a website login page for which you have a TOTP stored in Bitwarden
2. Click on the Bitwarden extension and select the suggested login card
3. Paste the contents from your clipboard.

## Expected Result
The expected result is the TOTP should be copied to your clipboard after selecting the login item from the extension if the item has TOTP. Also, if a custom value for the "Clear Clipboard" option is chosen, then the extension should clear the clipboard after the specified time.

## Actual Result
The TOTP is never copied to the clipboard. As a result, the clipboard is also not cleared after the specified time.

## Environment
Device: MacBook Pro (13-inch, M1, 2020)
OS: macOS Big Sur 11.5.2 (20G95)
Browser: Google Chrome 93.0.4577.63 (Official Build) (arm64)
Extension Version: Bitwarden 1.52.1
Application Version: Bitwarden 1.27.1 (531)

## Additional Context
There are only two extensions installed, the other being uBlock Origin. The extension works as expected on Windows 10 Enterprise x64 on Google Chrome with the latest version of Bitwarden (application and extension).

### PR DESCRIPTION
**Pull request by eliykat**
## Objective

Fix #2053:

> When using the Bitwarden extension from the Chrome Web Store, the extension does not automatically copy the TOTP after clicking on the appropriate login from the extension.

This only affects copying from `current-tab.component`. It appears that the popup closes before the copy-to-clipboard operation finishes - despite that being a completely synchronous operation.

This appeared around Chrome 93. Most affected users were using Chrome 93 on MacOS, which I could reproduce, and there was 1 report on Brave, which I couldn't reproduce. I couldn't find any release notes that indicate what change might have caused this, and it's unclear whether it's a Chrome or upstream Chromium issue.

## Code changes

* `current-tab.component` - add a short (50ms) delay to closing the window.

I don't like using `setTimeout` to avoid race conditions, but I couldn't find any underlying cause to be able to provide a better solution. We should be moving away from these deprecated clipboard APIs anyway, which I've created a tech debt ticket for, so the need for this workaround can be revisited at that time.

### CODE REVIEW

File: src/popup/vault/current-tab.component.ts [hunk 1]
```diff
@@ -156,7 +156,8 @@ export class CurrentTabComponent implements OnInit, OnDestroy {
                 this.platformUtilsService.copyToClipboard(this.totpCode, { window: window });
             }
             if (this.popupUtilsService.inPopup(window)) {
-                BrowserApi.closePopup(window);
+                // Slight delay to fix bug in Chrome where popup closes without copying totp to clipboard
+                setTimeout(() => BrowserApi.closePopup(window), 50);
```
Comment (kspearrin) [inline src/popup/vault/current-tab.component.ts:160]: Should this be conditional to exclude Firefox?

Comment (eliykat) [reply src/popup/vault/current-tab.component.ts]: Fair call - I've amended this to exclude Firefox and Safari.

**Review by kspearrin — APPROVED** [review]

File: src/popup/vault/current-tab.component.ts (hunk 1 above)
Comment (pradhyumk) [reply src/popup/vault/current-tab.component.ts]: @eliykat I just noticed this merge req, but you might also want to consider adding an exclusion for Windows because the extension works as expected on Windows.
